before:
  hooks:
    - env GO111MODULE=on go test ./...
builds:
  - 
    env:
      - GO111MODULE=on
    main: main.go
    binary: voicebr
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
    goarm:
      - 6
      - 7
    ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.ShortCommit}} -X main.buildTime={{.Date}}
sign:
  artifacts: checksum

snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"
