---
- hosts: default
  tasks:
    - name: build executable
      delegate_to: localhost
      environment:
        GOOS: linux
        GOARCH: arm
        GOARM: 6
      make:
        target: all
        chdir: "{{ lookup('env', 'PWD') }}"
    - name: deploy voicebr
      become: true
      copy:
        src: "{{ lookup('env', 'PWD') }}/bin/voicebr"
        dest: "/usr/local/bin/voicebr"
        mode: a+x
    - name: deploy voicebr cnsas
      become: true
      copy:
        src: "{{ lookup('env', 'PWD') }}/priv/run-voicebr_cnsas.sh"
        dest: "/home/pi/run_voicebr_cnsas.sh"
        mode: a+x
    - name: deploy service configuration
      become: true
      copy:
        src: "{{ lookup('env', 'PWD') }}/priv/voicebr.service"
        dest: "/etc/systemd/system/voicebr.service"
        mode: a+x
    - name: deploy private key
      become: true
      copy:
        src: "{{ lookup('env', 'PWD') }}/priv/private_key.pem"
        dest: "/home/pi/.voicebr-private_key.pem"
        mode: a+x
    - name: restart service
      become: true
      systemd:
        daemon_reload: true
        enabled: true
        state: restarted
        name: voicebr
